---
- name: Disable other NTP services
  include_tasks: disable-other-ntp-services.yml
  when: chrony_service_enabled or chrony_service_state != 'stopped'

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: "{{ __chrony_config_location }}"
    owner: root
    group: root
    mode: 0644
  notify: restart chrony

- name: Set timezone
  timezone:
    name: "{{ chrony_timezone }}"
  when: chrony_timezone is not none
  notify: restart chrony
