---
- name: Include OS-specific variables
  tags: [chrony, ntp]
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

- import_tasks: install.yml
  tags: [chrony, ntp]

- import_tasks: configure.yml
  tags: [chrony, ntp]
